[package]
name = "rusty-hooks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.60"
futures = "0.3.25"
reqwest = "0.11.14"
serde = { version = "1.0.150", features = ["derive"] }
serde_json = "1.0.89"
timer = "0.2.0"
tokio = { version = "1.23.0", features = ["full", "time"] }
