on:
  workflow_call:

name: Build Release Binaries

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - name: Restore From Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ runner.os }}-build-release-nightly-toolchain-${{ hashFiles('**/Cargo.toml') }}
          key: ${{ runner.os }}-build-release-nightly-toolchain
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ARCHIVE_TYPES: ${{ matrix.archive }}
          RUSTTARGET: ${{ matrix.target }}
          TOOLCHAIN_VERSION: nightly
