name: docker-build-and-push

on:
  workflow_call:
    inputs:
      image-tag:
        description: 'Tag to use for binaries'
        default: 'latest'
        required: false
        type: string
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Tag to use for binaries'
        default: 'latest'
        required: false
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            mmbarness/rusty-hooks:latest
            mmbarness/rusty-hooks:${{inputs.image-tag}}
          cache-from: type=registry,ref=mmbarness/rusty-hooks:${{inputs.image-tag}}
          cache-to: type=inline
