on:
  release:
    types: [created]
  workflow_dispatch:

name: Build Release Artifacts

jobs:
  artifacts:
    name: ${{ matrix.build_job }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - build_job: binaries
          - build_job: docker
    steps:
      - name: binaries
        uses: ./github/workflows/build_release_binaries.yml
      - name: call workflow
        uses: ./github/workflows/docker.yml
