on:
  release:
    types: [created]
  workflow_dispatch:

name: Build Release Artifacts

jobs:
  binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: binaries
        uses: ./github/workflows/build_release_binaries.yml
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: call workflow
        uses: ./github/workflows/docker.yml
