on:
  release:
    types: [created]
  workflow_dispatch:

name: Build Release Artifacts

jobs:
  binaries:
    uses: ./.github/workflows/build_release_binaries.yml
  docker:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
